# included templates
include:
  # Docker template
  - remote: "https://gitlab.com/to-be-continuous/docker/-/raw/5.13/templates/gitlab-ci-docker.yml"

# variables
variables:
  DOCKER_HADOLINT_DISABLED: "true"
  DOCKER_SNAPSHOT_IMAGE: vcucchie/oreczml-js-interface
  DOCKER_RELEASE_IMAGE: vcucchie/oreczml-js-interface
  DOCKER_PROD_PUBLISH_STRATEGY: none


# your pipeline stages
stages:
  - build
  - test
  - package-build
  - package-test
  - infra
  - deploy
  - acceptance
  - publish
  - infra-prod
  - production